version: '3.8'

services:
  luminlex:
    image: luminlex-app:latest
    container_name: luminlex-app
    ports:
      - "8502:8501"
    restart: unless-stopped
    volumes:
      - /opt/streamlit/luminlex:/app:ro
