# Rosetta API Keys Configuration

kimi_api_key = "sk-XUiZxmLE0iWRKc2x5EF0qjtmnkITr3MrR0qeQTA3TP5gPd1e"
deepseek_api_key = "sk-00d61fc7415a4baea3d985b129ff37c7"
qwen_api_key = "sk-553fe4692b0445dfa874588431115626"
minimax_api_key = "sk-api-tVF69xid9gEoArrz7LSSFc0guJRWRkBWblytVV3tcR0cC1YaPYPWvplOAbw0kfoklWDYyxArUv4KADSwaKj24peErS0raPXOo_KGXfBsq_GPTm11VhqDckI"
zhipuai_api_key = "666bbea32fb64b308c875681d2fff636.RzdqCasOkhZ6Lu5p"